### ISSUE TITLE
Data clean up and prep

### ISSUE THREAD

**Issue by iamMoid** [UBC-MDS/imdb_dashboard#13]

**Comment by ming0701** [comment]
Due to the file size, I can only upload the files to google drive. Please take a look and let me know if you have any comments.

Dataset:
https://drive.google.com/file/d/1dxafJmADQY8ZCn-0h49HVIXNPS8Nhtry/view?usp=sharing

Code for cleaning:
https://drive.google.com/file/d/1X6E-kqKdKWO0MqOWkgPb82DYAavk0E0m/view?usp=sharing

**Comment by ming0701** [comment]
Further updates:
- explode genres
- change datatype of runtime and year to int
https://github.com/UBC-MDS/imdb_dashboard/blob/data_clean/data/imdb_data_cleaning.ipynb
https://drive.google.com/file/d/1K8KYDfmdyuisyjSYxSwS83cOEItObNSD/view?usp=sharing

**Comment by ming0701** [comment]
- include actor/actress/self only for principals
- exclude movies before 1970
https://github.com/UBC-MDS/imdb_dashboard/blob/data_clean/data/imdb_data_cleaning.ipynb
https://drive.google.com/file/d/1NVGdl62Gd79VvJ1cKCRxSGfG0KvZ_HOb/view?usp=sharing

**Comment by ming0701** [comment]
- include data for year 2011-2020 only
https://github.com/UBC-MDS/imdb_dashboard/blob/main/data/imdb_data_cleaning.ipynb
https://drive.google.com/file/d/1SKh8rQVJhc8IABZFnJWKLdU3ax8M3AeA/view?usp=sharing

**Comment by iamMoid** [comment]
Thanks for all your efforts on data clean-up! We are still heavy on the data with over 500k rows. As discussed, let us filter the data down to around 180k rows by keeping the following genres:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ibaad/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ibaad/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



genres | rows
-- | --
Action | 34057
Crime | 22614
Horror | 35060
Mystery | 15133
Romance | 30120
Sci-Fi | 9850
Thriller | 38078



</body>

</html>

**Comment by ming0701** [comment]
- include popular genres only
https://github.com/UBC-MDS/imdb_dashboard/blob/main/data/imdb_2011-2020.csv
https://github.com/UBC-MDS/imdb_dashboard/blob/main/data/imdb_data_cleaning.ipynb
