### ISSUE TITLE
Improvement: Improve app performance

### ISSUE THREAD

**Issue by NikitaShymberg** [UBC-MDS/imdb_dashboard#47]

**Comment by ming0701** [comment]
[db9a99b7a281c58555d7a440eda09a9928b81566](https://github.com/UBC-MDS/imdb_dashboard/pull/56/commits/db9a99b7a281c58555d7a440eda09a9928b81566)
https://github.com/UBC-MDS/imdb_dashboard/pull/56/commits/f967ee2ba0506c56b90f8ec72f40249c0e1d2b40
